SET ECHO ON

CREATE USER JRUEDAC IDENTIFIED BY JRUEDAC
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP;

GRANT CONNECT TO JRUEDAC;
GRANT RESOURCE TO JRUEDAC;
GRANT CREATE VIEW TO JRUEDAC;

ALTER USER JRUEDAC QUOTA UNLIMITED ON USERS;
