SET ECHO ON

DROP VIEW VW_REPORTE_PERSONAS;

DROP TRIGGER TRG_PERSONA_ID;

DROP SEQUENCE SEQ_PERSONA;

DROP TABLE DATOS_PERSONALES CASCADE CONSTRAINTS;

CREATE TABLE DATOS_PERSONALES (
ID_PERSONA NUMBER(10) NOT NULL,
NOMBRE VARCHAR2(50) NOT NULL,
APELLIDOS VARCHAR2(80) NOT NULL,
EDAD NUMBER(3) NOT NULL,
CEDULA VARCHAR2(20) NOT NULL,
FECHA_NACIMIENTO DATE,
TELEFONO VARCHAR2(20),
EMAIL VARCHAR2(80),
DIRECCION VARCHAR2(120),
FECHA_REGISTRO DATE DEFAULT SYSDATE,
CONSTRAINT PK_DATOS_PERSONALES PRIMARY KEY (ID_PERSONA),
CONSTRAINT UK_DATOS_PERSONALES_CEDULA UNIQUE (CEDULA)
);

CREATE SEQUENCE SEQ_PERSONA
START WITH 1
INCREMENT BY 1
NOCACHE;

CREATE OR REPLACE TRIGGER TRG_PERSONA_ID
BEFORE INSERT ON DATOS_PERSONALES
FOR EACH ROW
BEGIN
IF :NEW.ID_PERSONA IS NULL THEN
SELECT SEQ_PERSONA.NEXTVAL
INTO :NEW.ID_PERSONA
FROM DUAL;
END IF;
END;
/
SHOW ERRORS

CREATE OR REPLACE VIEW VW_REPORTE_PERSONAS AS
SELECT
ID_PERSONA,
NOMBRE,
APELLIDOS,
CEDULA,
EDAD,
FECHA_NACIMIENTO,
TELEFONO,
EMAIL,
DIRECCION,
FECHA_REGISTRO
FROM DATOS_PERSONALES;

SHOW ERRORS VIEW VW_REPORTE_PERSONAS

INSERT INTO DATOS_PERSONALES
(NOMBRE, APELLIDOS, EDAD, CEDULA, FECHA_NACIMIENTO, TELEFONO, EMAIL, DIRECCION)
VALUES
('Jesus Daniel', 'Rueda Castillo', 20, '1234567890',
TO_DATE('15/05/2004','DD/MM/YYYY'), '3001234567',
'jrueda51@udi.edu.co', 'Barrancabermeja');

COMMIT;

SELECT * FROM VW_REPORTE_PERSONAS;
