SET ECHO ON

ALTER TABLE DATOS_PERSONALES ADD FECHA_REGISTRO DATE DEFAULT SYSDATE;

CREATE OR REPLACE VIEW VW_REPORTE_PERSONAS AS
SELECT
ID_PERSONA,
NOMBRE,
APELLIDOS,
CEDULA,
EDAD,
FECHA_NACIMIENTO,
TELEFONO,
EMAIL,
DIRECCION,
FECHA_REGISTRO
FROM DATOS_PERSONALES;

SELECT * FROM VW_REPORTE_PERSONAS;

